from __future__ import annotations

import copy
from datetime import datetime, timezone


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


SEED_IR = {
    "id": "rs_leave_001",
    "name": "员工请假申请",
    "idea": "员工提交请假申请，经理审批后通知 HR 记录结果。要求有PC和移动端支持。",
    "domain": {"taskType": "申请与审批", "templateId": "approval_lite", "assumptions": []},
    "nodes": {
        "g1": {
            "id": "g1",
            "kind": "goal",
            "title": "消除线下请假确认成本，实现信息闭环",
            "description": "在线提交至最终结果反馈的总耗时低于 1 小时。",
            "status": "confirmed",
            "confidence": 1.0,
            "source": {"type": "user", "text": "用户原始想法"},
        },
        "c1": {
            "id": "c1",
            "kind": "capability",
            "title": "请假申请管理",
            "description": "支持员工提交、查看请假申请",
            "status": "confirmed",
            "confidence": 0.9,
            "scopeStatus": "in_scope",
            "source": {"type": "ai"},
            "priority": "P0",
        },
        "c2": {
            "id": "c2",
            "kind": "capability",
            "title": "审批流转",
            "description": "支持经理审批、通知流转",
            "status": "confirmed",
            "confidence": 0.9,
            "scopeStatus": "in_scope",
            "source": {"type": "ai"},
            "priority": "P0",
        },
        "a_employee": {
            "id": "a_employee",
            "kind": "actor",
            "title": "员工",
            "description": "发起请假申请",
            "status": "confirmed",
            "confidence": 1.0,
            "source": {"type": "user"},
        },
        "a_manager": {
            "id": "a_manager",
            "kind": "actor",
            "title": "直属经理",
            "description": "负责审核直接下属请假",
            "status": "confirmed",
            "confidence": 1.0,
            "source": {"type": "user"},
        },
        "a_hr": {
            "id": "a_hr",
            "kind": "actor",
            "title": "HR",
            "description": "归档与核对",
            "status": "confirmed",
            "confidence": 1.0,
            "source": {"type": "user"},
        },
        "t1": {
            "id": "t1",
            "kind": "task",
            "title": "员工在线提交请假单",
            "status": "confirmed",
            "confidence": 0.9,
            "source": {"type": "ai"},
            "owner": "员工",
            "result": "生成待审批记录",
        },
        "t2": {
            "id": "t2",
            "kind": "task",
            "title": "经理审批待办",
            "status": "confirmed",
            "confidence": 0.9,
            "source": {"type": "ai"},
            "owner": "直属经理",
            "result": "通过或拒绝",
        },
        "o_leave": {
            "id": "o_leave",
            "kind": "business_object",
            "title": "请假申请单",
            "description": "承载请假时间、理由、审批状态等信息",
            "status": "ai_assumption",
            "confidence": 0.86,
            "source": {"type": "ai", "text": "由审批类模板推断"},
        },
        "f1": {
            "id": "f1",
            "kind": "flow",
            "title": "请假申请审批流程",
            "trigger": "员工提交请假申请",
            "status": "ai_assumption",
            "confidence": 0.82,
            "slots": ["slot_return_rule"],
            "source": {"type": "ai"},
        },
        "s1": {
            "id": "s1",
            "kind": "flow_step",
            "title": "填写请假表单",
            "stepType": "用户输入",
            "actor": "员工",
            "swimlane": "员工",
            "input": ["请假类型", "日期范围", "事由"],
            "output": ["请假单对象(Draft)"],
            "status": "confirmed",
            "confidence": 0.95,
            "source": {"type": "ai"},
        },
        "s2": {
            "id": "s2",
            "kind": "flow_step",
            "title": "校验可用余额",
            "stepType": "系统规则",
            "actor": "系统",
            "swimlane": "系统",
            "input": ["请假单", "用户余额"],
            "output": ["通过/拦截"],
            "status": "ai_assumption",
            "confidence": 0.8,
            "source": {"type": "ai"},
        },
        "s3": {
            "id": "s3",
            "kind": "flow_step",
            "title": "经理审批台",
            "stepType": "界面操作",
            "actor": "直属经理",
            "swimlane": "直属经理",
            "input": ["请假单(Pending)"],
            "output": ["通过/退回"],
            "status": "needs_confirmation",
            "confidence": 0.7,
            "source": {"type": "ai"},
        },
        "s4": {
            "id": "s4",
            "kind": "flow_step",
            "title": "发送通知与归档",
            "stepType": "后台动作",
            "actor": "系统",
            "swimlane": "系统",
            "input": ["审批结果"],
            "output": ["邮件通知", "HR记录"],
            "status": "confirmed",
            "confidence": 0.9,
            "source": {"type": "ai"},
        },
        "screen_employee_form": {
            "id": "screen_employee_form",
            "kind": "screen",
            "title": "新建请假申请",
            "description": "员工提交请假表单页面",
            "status": "ai_assumption",
            "confidence": 0.8,
            "source": {"type": "ai"},
        },
        "screen_mgr_detail": {
            "id": "screen_mgr_detail",
            "kind": "screen",
            "title": "审批详情",
            "description": "查看单据详情并审批",
            "status": "confirmed",
            "confidence": 0.9,
            "source": {"type": "ai"},
        },
        "ui_emp_submit_btn": {
            "id": "ui_emp_submit_btn",
            "kind": "ui_component",
            "title": "SubmitButton",
            "description": "提交按钮",
            "status": "confirmed",
            "confidence": 0.9,
            "source": {"type": "ai"},
        },
        "ui_mgr_approve_btn": {
            "id": "ui_mgr_approve_btn",
            "kind": "ui_component",
            "title": "ApproveButton",
            "description": "通过按钮",
            "status": "confirmed",
            "confidence": 0.9,
            "source": {"type": "ai"},
        },
        "ui_mgr_reject_btn": {
            "id": "ui_mgr_reject_btn",
            "kind": "ui_component",
            "title": "RejectButton",
            "description": "退回按钮",
            "status": "confirmed",
            "confidence": 0.9,
            "source": {"type": "ai"},
        },
    },
    "links": [
        {"id": "l1", "sourceId": "c1", "targetId": "g1", "type": "realizes", "status": "active", "source": {"type": "ai"}},
        {"id": "l2", "sourceId": "c2", "targetId": "g1", "type": "realizes", "status": "active", "source": {"type": "ai"}},
        {"id": "l3", "sourceId": "s1", "targetId": "s2", "type": "precedes", "status": "active", "source": {"type": "ai"}},
        {"id": "l4", "sourceId": "s2", "targetId": "s3", "type": "precedes", "status": "active", "source": {"type": "ai"}},
        {"id": "l5", "sourceId": "s3", "targetId": "s4", "type": "precedes", "status": "active", "source": {"type": "ai"}},
        {"id": "l6", "sourceId": "a_employee", "targetId": "t1", "type": "performed_by", "status": "active", "source": {"type": "ai"}},
        {"id": "l7", "sourceId": "a_manager", "targetId": "t2", "type": "performed_by", "status": "active", "source": {"type": "ai"}},
        {"id": "l8", "sourceId": "screen_employee_form", "targetId": "a_employee", "type": "reads", "status": "active", "source": {"type": "ai"}},
        {"id": "l9", "sourceId": "screen_mgr_detail", "targetId": "a_manager", "type": "reads", "status": "active", "source": {"type": "ai"}},
        {"id": "l10", "sourceId": "ui_emp_submit_btn", "targetId": "screen_employee_form", "type": "displayed_on", "status": "active", "source": {"type": "ai"}},
        {"id": "l11", "sourceId": "ui_mgr_approve_btn", "targetId": "screen_mgr_detail", "type": "displayed_on", "status": "active", "source": {"type": "ai"}},
        {"id": "l12", "sourceId": "ui_mgr_reject_btn", "targetId": "screen_mgr_detail", "type": "displayed_on", "status": "active", "source": {"type": "ai"}},
        {"id": "l13", "sourceId": "ui_emp_submit_btn", "targetId": "s1", "type": "triggered_by", "status": "active", "source": {"type": "ai"}},
        {"id": "l14", "sourceId": "ui_mgr_reject_btn", "targetId": "s3", "type": "triggered_by", "status": "active", "source": {"type": "ai"}},
    ],
    "slots": {
        "slot_return_rule": {
            "id": "slot_return_rule",
            "ownerNodeId": "f1",
            "name": "退回后处理规则",
            "description": "经理退回申请后，员工如何接收通知以及重新提交流程。",
            "expectedKinds": ["rule", "flow_step", "state_transition", "ui_component"],
            "arity": "many",
            "status": "expanding",
            "choiceGroupId": "cg1",
            "context": {"projectionHints": ["system", "data", "ui"], "relatedNodeIds": ["s3", "o_leave"]},
        }
    },
    "choiceGroups": {
        "cg1": {
            "id": "cg1",
            "slotId": "slot_return_rule",
            "selectionMode": "single",
            "status": "open",
            "choices": [
                {
                    "id": "cand-1",
                    "title": "补充退回重提流程",
                    "rationale": "在经理退回后，自动生成待办并允许员工重提。",
                    "proposedNodeIds": [],
                    "proposedLinkIds": [],
                    "impactPreview": {
                        "affectedGoals": ["g1"],
                        "affectedActors": ["a_employee"],
                        "affectedFlows": ["f1"],
                        "affectedObjects": ["o_leave"],
                        "affectedScreens": ["screen_employee_form"],
                        "resolvedIssues": ["gap-1"],
                    },
                    "status": "candidate",
                }
            ],
        }
    },
    "proposals": {},
    "issues": {
        "gap-1": {
            "id": "gap-1",
            "title": "退回逻辑分支断层",
            "description": "经理退回表单后，没有定义员工接收通知与重新提交步骤。",
            "severity": "high",
            "category": "flow_gap",
            "relatedNodeIds": ["s3"],
            "suggestedProjection": "system",
            "suggestedAction": "请补充异常分支。",
            "status": "open",
            "source": {"type": "ai"},
        },
        "gap-2": {
            "id": "gap-2",
            "title": "通知渠道未定义",
            "description": "未说明邮件、短信或企业微信通知策略。",
            "severity": "medium",
            "category": "scope_risk",
            "relatedNodeIds": ["s4"],
            "suggestedProjection": "system",
            "suggestedAction": "补充通知能力定义。",
            "status": "open",
            "source": {"type": "ai"},
        },
    },
    "projections": {
        "goal": {"rootGoalIds": ["g1"], "expandedNodeIds": ["g1", "c1", "c2"]},
        "role": {"actorIds": ["a_employee", "a_manager", "a_hr"], "visibleColumns": ["responsibility"]},
        "system": {"flowIds": ["f1"], "swimlaneBy": "actor", "highlightedNodeIds": []},
        "data": {"objectIds": ["o_leave"], "showStates": True, "showFields": True},
        "ui": {"roleViewIds": [], "activeActorId": "a_employee", "activeScreenId": "screen_employee_form"},
    },
    "audit": {
        "createdAt": "2026-05-09T00:00:00Z",
        "updatedAt": "2026-05-09T00:00:00Z",
        "sourceSummary": [{"type": "user", "text": "员工提交请假申请，经理审批后通知 HR 记录结果。"}],
    },
}


def build_seed_ir(prompt: str | None = None) -> dict:
    data = copy.deepcopy(SEED_IR)
    if prompt and prompt.strip():
        data["idea"] = prompt.strip()
        data["audit"]["sourceSummary"] = [{"type": "user", "text": prompt.strip()}]
    data["audit"]["updatedAt"] = now_iso()
    return data
