APP_STARTING = "app_starting"
APP_STARTED = "app_started"
APP_START_FAILED = "app_start_failed"

HTTP_REQUEST_COMPLETED = "http_request_completed"
HTTP_REQUEST_FAILED = "http_request_failed"
GLOBAL_EXCEPTION_CAUGHT = "global_exception_caught"
HTTP_EXCEPTION_CAUGHT = "http_exception_caught"

DB_CONNECTION_URL_NORMALIZED = "db_connection_url_normalized"
DB_INIT_STARTED = "db_init_started"
DB_INIT_COMPLETED = "db_init_completed"
DB_INIT_FAILED = "db_init_failed"
DB_BOOTSTRAP_STARTED = "db_bootstrap_started"
DB_BOOTSTRAP_COMPLETED = "db_bootstrap_completed"
DB_BOOTSTRAP_FAILED = "db_bootstrap_failed"
DB_MIGRATION_STARTED = "db_migration_started"
DB_MIGRATION_COMPLETED = "db_migration_completed"
DB_MIGRATION_FAILED = "db_migration_failed"
DB_SQLITE_REPAIR_STARTED = "db_sqlite_repair_started"
DB_SQLITE_REPAIR_COMPLETED = "db_sqlite_repair_completed"
DB_SQLITE_REPAIR_FAILED = "db_sqlite_repair_failed"
DB_STAMP_STARTED = "db_stamp_started"
DB_STAMP_COMPLETED = "db_stamp_completed"
DB_STAMP_FAILED = "db_stamp_failed"

LLM_API_CALL_ATTEMPT = "llm_api_call_attempt"
LLM_API_CALL_COMPLETED = "llm_api_call_completed"
LLM_API_CALL_FAILED = "llm_api_call_failed"
LLM_API_CALL_ALL_ATTEMPTS_FAILED = "llm_api_call_all_attempts_failed"
LLM_RESPONSE_INVALID = "llm_response_invalid"
LLM_RETRY_SCHEDULED = "llm_retry_scheduled"
LLM_PROMPT_SAMPLE = "llm_prompt_sample"
LLM_RESPONSE_SAMPLE = "llm_response_sample"

AI_OPERATION_COMPLETED = "ai_operation_completed"
AI_OPERATION_FAILED = "ai_operation_failed"
AI_OPERATION_RESULT = "ai_operation_result"

AUTH_LOGIN_SUCCEEDED = "auth_login_succeeded"
AUTH_LOGIN_FAILED = "auth_login_failed"
AUTH_PERMISSION_DENIED = "auth_permission_denied"
LLM_CONFIG_SAVED = "llm_config_saved"
LLM_CONFIG_RESOLVED = "llm_config_resolved"
LLM_CONFIG_MISSING = "llm_config_missing"

AUDIT_LOG_WRITE_COMPLETED = "audit_log_write_completed"
AUDIT_LOG_WRITE_FAILED = "audit_log_write_failed"

CHOICE_GROUP_CREATE_REQUESTED = "choice_group_create_requested"
CHOICE_GROUP_CREATED = "choice_group_created"
CHOICE_GROUP_GENERATION_FAILED = "choice_group_generation_failed"
CHOICE_GROUP_REGENERATED = "choice_group_regenerated"
CHOICE_GROUP_RESOLVED = "choice_group_resolved"

AI_ADD_SESSION_CREATED = "ai_add_session_created"
AI_ADD_DRAFT_CREATED = "ai_add_draft_created"
AI_ADD_DRAFT_DISCARDED = "ai_add_draft_discarded"
AI_ADD_LLM_PARSE_FAILED = "ai_add_llm_parse_failed"
AI_EXPLAIN_COMPLETED = "ai_explain_completed"
AI_EXPLAIN_FAILED = "ai_explain_failed"
PROJECT_INTERVIEW_MESSAGE_PROCESSED = "project_interview_message_processed"
PROJECT_INTERVIEW_COMPLETE_FAILED = "project_interview_complete_failed"

FINDING_DETECTION_STARTED = "finding_detection_started"
FINDING_DETECTION_COMPLETED = "finding_detection_completed"
FINDING_DETECTION_FAILED = "finding_detection_failed"
ISSUE_REPAIR_DRAFT_CREATED = "issue_repair_draft_created"
ISSUE_REPAIR_FAILED = "issue_repair_failed"
PERCEPTION_JOB_STARTED = "perception_job_started"
PERCEPTION_JOB_COMPLETED = "perception_job_completed"
PERCEPTION_JOB_FAILED = "perception_job_failed"
PERCEPTION_SLOT_FILLING_DRAFT_CREATED = "perception_slot_filling_draft_created"
