export const auditActionTypeLabels: Record<string, string> = {
  accept_choice: '采纳候选方案',
  ai_action: 'AI 操作',
  ai_draft_applied_by_user: '采纳 AI 草稿',
  ai_draft_conflict_detected: '检测到 AI 草稿冲突',
  ai_draft_generated: '生成 AI 草稿',
  create_ac: '新增验收标准',
  create_acceptance_criterion: '新增验收标准',
  create_actor: '新增参与者',
  create_business_object: '新增业务对象',
  create_business_object_attribute: '新增对象属性',
  create_choice_group: '生成方案组',
  create_confirmation_task: '创建确认任务',
  create_feature: '新增功能',
  create_flow: '新增业务流',
  create_flow_step: '新增流程步骤',
  create_scenario: '新增场景',
  create_task: '创建任务',
  delete_ac: '删除验收标准',
  delete_acceptance_criterion: '删除验收标准',
  delete_actor: '删除参与者',
  delete_business_object: '删除业务对象',
  delete_business_object_attribute: '删除对象属性',
  delete_feature: '删除功能',
  delete_flow: '删除业务流',
  delete_flow_step: '删除流程步骤',
  delete_scenario: '删除场景',
  discard_choice_group: '丢弃修复候选组',
  discard_shadow_draft: '丢弃影子草稿',
  generation_choice_accepted: '采纳生成候选方案',
  generation_choice_group_created: '生成候选方案组',
  generation_choice_group_discarded: '丢弃生成候选组',
  generation_choice_group_stale: '候选方案已过期',
  generation_choice_rejected: '拒绝生成候选方案',
  issue_repair_confirmed: '确认问题修复',
  issue_repair_discarded: '丢弃问题修复',
  member_added: '添加项目成员',
  member_removed: '移除项目成员',
  member_role_changed: '更新成员角色',
  member_role_updated: '更新成员角色',
  member_status_changed: '更新成员状态',
  member_invitation_accepted: '接受成员邀请',
  member_invitation_declined: '拒绝成员邀请',
  member_invitation_revoked: '撤销成员邀请',
  refine_user_requirements: 'AI 精炼用户需求',
  regenerate_choice_group: '重新生成方案组',
  regenerate_shadow_draft: '重新生成影子草稿',
  reject_choice: '拒绝候选方案',
  reject_task: '审批驳回',
  reorder_flow_steps: '调整流程步骤顺序',
  set_kano_status: '更新 Kano 分析状态',
  skip_kano: '跳过 Kano 分析',
  stage_transition_forced: '强制推进阶段',
  stage_transition_unlocked: '解锁阶段',
  supersede_confirmation_task: '替换确认任务',
  task_approved: '审批通过',
  task_cancelled: '取消任务',
  task_created: '创建任务',
  task_rejected: '审批驳回',
  task_superseded: '任务已冲销',
  task_superseded_by_node_update: '节点变更导致任务失效',
  test_action: '测试操作',
  unlock_stage_gate: '解锁阶段门',
  update_ac: '更新验收标准',
  update_acceptance_criterion: '更新验收标准',
  update_actor: '更新参与者',
  update_business_object: '更新业务对象',
  update_business_object_attribute: '更新对象属性',
  update_confirmation_status: '更新确认状态',
  batch_update_confirmation_status: '批量更新确认状态',
  update_confirmation_task: '更新确认任务',
  update_feature: '更新功能',
  update_flow: '更新业务流',
  update_flow_step: '更新流程步骤',
  update_scenario: '更新场景',
  update_scope: '更新范围决策',
  update_user_requirements: '更新用户需求',
  approve_task: '审批通过',
  commit_shadow_draft: '提交影子草稿',
  complete_confirmation_task: '完成确认任务',
};

export const getAuditActionTypeLabel = (actionType: string | null | undefined) => {
  if (!actionType) return '未知操作';
  return auditActionTypeLabels[actionType] || actionType;
};

export const withAuditActionTypeLabel = <T extends { actionType?: string; action_type?: string }>(log: T) => {
  const actionType = log.actionType || log.action_type;
  return {
    ...log,
    actionTypeLabel: getAuditActionTypeLabel(actionType),
  };
};
