export const auditActionTypeLabels: Record<string, string> = {
  accept_choice: '采纳候选方案',
  ai_action: 'AI 操作',
  ai_draft_applied_by_user: '采纳 AI 草稿',
  ai_draft_conflict_detected: '检测到 AI 草稿冲突',
  ai_draft_generated: '生成 AI 草稿',
  create_ac: '新增验收标准',
  create_acceptance_criterion: '新增验收标准',
  create_actor: '新增参与者',
  create_business_object: '新增业务对象',
  create_business_object_attribute: '新增对象属性',
  create_choice_group: '生成方案组',
  create_confirmation_task: '创建确认任务',
  create_feature: '新增功能',
  create_flow: '新增业务流',
  create_flow_step: '新增流程步骤',
  create_scenario: '新增场景',
  create_task: '创建任务',
  delete_ac: '删除验收标准',
  delete_acceptance_criterion: '删除验收标准',
  delete_actor: '删除参与者',
  delete_business_object: '删除业务对象',
  delete_business_object_attribute: '删除对象属性',
  delete_feature: '删除功能',
  delete_flow: '删除业务流',
  delete_flow_step: '删除流程步骤',
  delete_scenario: '删除场景',
  discard_choice_group: '丢弃修复候选组',
  discard_shadow_draft: '丢弃影子草稿',
  generation_choice_accepted: '采纳生成候选方案',
  generation_choice_group_created: '生成候选方案组',
  generation_choice_group_discarded: '丢弃生成候选组',
  generation_choice_group_stale: '候选方案已过期',
  generation_choice_rejected: '拒绝生成候选方案',
  issue_repair_confirmed: '确认问题修复',
  issue_repair_discarded: '丢弃问题修复',
  member_added: '添加项目成员',
  member_removed: '移除项目成员',
  member_role_changed: '更新成员角色',
  member_role_updated: '更新成员角色',
  member_status_changed: '更新成员状态',
  member_invitation_accepted: '接受成员邀请',
  member_invitation_declined: '拒绝成员邀请',
  member_invitation_revoked: '撤销成员邀请',
  refine_user_requirements: 'AI 精炼用户需求',
  regenerate_choice_group: '重新生成方案组',
  regenerate_shadow_draft: '重新生成影子草稿',
  reject_choice: '拒绝候选方案',
  reject_task: '审批驳回',
  reorder_flow_steps: '调整流程步骤顺序',
  set_kano_status: '更新 Kano 分析状态',
  skip_kano: '跳过 Kano 分析',
  stage_transition_forced: '强制推进阶段',
  stage_transition_unlocked: '解锁阶段',
  supersede_confirmation_task: '替换确认任务',
  task_approved: '审批通过',
  task_cancelled: '取消任务',
  task_created: '创建任务',
  task_rejected: '审批驳回',
  task_superseded: '任务已冲销',
  task_superseded_by_node_update: '节点变更导致任务失效',
  test_action: '测试操作',
  unlock_stage_gate: '解锁阶段门',
  update_ac: '更新验收标准',
  update_acceptance_criterion: '更新验收标准',
  update_actor: '更新参与者',
  update_business_object: '更新业务对象',
  update_business_object_attribute: '更新对象属性',
  update_confirmation_status: '更新确认状态',
  batch_update_confirmation_status: '批量更新确认状态',
  update_confirmation_task: '更新确认任务',
  update_feature: '更新功能',
  update_flow: '更新业务流',
  update_flow_step: '更新流程步骤',
  update_scenario: '更新场景',
  update_scope: '更新范围决策',
  update_user_requirements: '更新用户需求',
  update_project_locale: '更新项目内容语言',
  approve_task: '审批通过',
  commit_shadow_draft: '提交影子草稿',
  complete_confirmation_task: '完成确认任务',
  update_task: '更新任务',
  submit_task: '提交任务审核',
};

export const auditActionTypeLabelsEn: Record<string, string> = {
  accept_choice: 'Accept Candidate Option',
  ai_action: 'AI Action',
  ai_draft_applied_by_user: 'Adopt AI Draft',
  ai_draft_conflict_detected: 'AI Draft Conflict Detected',
  ai_draft_generated: 'AI Draft Generated',
  create_ac: 'Add Acceptance Criteria',
  create_acceptance_criterion: 'Add Acceptance Criteria',
  create_actor: 'Add Actor',
  create_business_object: 'Add Business Object',
  create_business_object_attribute: 'Add Object Attribute',
  create_choice_group: 'Generate Candidate Options Group',
  create_confirmation_task: 'Create Confirmation Task',
  create_feature: 'Add Feature',
  create_flow: 'Add Flow',
  create_flow_step: 'Add Flow Step',
  create_scenario: 'Add Scenario',
  create_task: 'Create Task',
  delete_ac: 'Delete Acceptance Criteria',
  delete_acceptance_criterion: 'Delete Acceptance Criteria',
  delete_actor: 'Delete Actor',
  delete_business_object: 'Delete Business Object',
  delete_business_object_attribute: 'Delete Object Attribute',
  delete_feature: 'Delete Feature',
  delete_flow: 'Delete Flow',
  delete_flow_step: 'Delete Flow Step',
  delete_scenario: 'Delete Scenario',
  discard_choice_group: 'Discard Repair Options Group',
  discard_shadow_draft: 'Discard Shadow Draft',
  generation_choice_accepted: 'Accept Generated Option',
  generation_choice_group_created: 'Generated Options Group',
  generation_choice_group_discarded: 'Discard Generated Options Group',
  generation_choice_group_stale: 'Candidate Option Expired',
  generation_choice_rejected: 'Reject Generated Option',
  issue_repair_confirmed: 'Confirm Issue Repair',
  issue_repair_discarded: 'Discard Issue Repair',
  member_added: 'Add Project Member',
  member_removed: 'Remove Project Member',
  member_role_changed: 'Update Member Role',
  member_role_updated: 'Update Member Role',
  member_status_changed: 'Update Member Status',
  member_invitation_accepted: 'Accept Member Invitation',
  member_invitation_declined: 'Decline Member Invitation',
  member_invitation_revoked: 'Revoke Member Invitation',
  refine_user_requirements: 'AI Refine User Requirements',
  regenerate_choice_group: 'Regenerate Options Group',
  regenerate_shadow_draft: 'Regenerate Shadow Draft',
  reject_choice: 'Reject Candidate Option',
  reject_task: 'Approval Rejected',
  reorder_flow_steps: 'Reorder Flow Steps',
  set_kano_status: 'Update Kano Analysis Status',
  skip_kano: 'Skip Kano Analysis',
  stage_transition_forced: 'Force Stage Transition',
  stage_transition_unlocked: 'Unlock Stage',
  supersede_confirmation_task: 'Supersede Confirmation Task',
  task_approved: 'Approval Approved',
  task_cancelled: 'Cancel Task',
  task_created: 'Create Task',
  task_rejected: 'Approval Rejected',
  task_superseded: 'Task Superseded',
  task_superseded_by_node_update: 'Task Invalidated by Node Update',
  test_action: 'Test Action',
  unlock_stage_gate: 'Unlock Stage Gate',
  update_ac: 'Update Acceptance Criteria',
  update_acceptance_criterion: 'Update Acceptance Criteria',
  update_actor: 'Update Actor',
  update_business_object: 'Update Business Object',
  update_business_object_attribute: 'Update Object Attribute',
  update_confirmation_status: 'Update Confirmation Status',
  batch_update_confirmation_status: 'Bulk Update Confirmation Status',
  update_confirmation_task: 'Update Confirmation Task',
  update_feature: 'Update Feature',
  update_flow: 'Update Flow',
  update_flow_step: 'Update Flow Step',
  update_project_locale: 'Update Project Content Language',
  update_scenario: 'Update Scenario',
  update_scope: 'Update Scope Decision',
  update_user_requirements: 'Update User Requirements',
  update_task: 'Update Task',
  submit_task: 'Submit Task for Review',
  approve_task: 'Approve Task',
  commit_shadow_draft: 'Submit Shadow Draft',
  complete_confirmation_task: 'Complete Confirmation Task',
};

export const getAuditActionTypeLabel = (actionType: string | null | undefined, lang: string = 'zh-CN') => {
  if (!actionType) return lang === 'zh-CN' ? '未知操作' : 'Unknown Operation';
  if (lang === 'en-US') {
    return auditActionTypeLabelsEn[actionType] || 'Unknown Operation';
  }
  return auditActionTypeLabels[actionType] || '未知操作';
};

export const getAuditSummary = (
  log: { actionType?: string; action_type?: string; summary?: string },
  lang: string = 'zh-CN',
) => {
  const actionType = log.actionType || log.action_type;
  const summary = log.summary?.trim();
  if (!summary) return getAuditActionTypeLabel(actionType, lang);
  if (/^[a-z][a-z0-9_]*$/.test(summary)) return getAuditActionTypeLabel(summary, lang);
  if (lang === 'en-US' && /[\u4e00-\u9fff]/.test(summary)) {
    return getAuditActionTypeLabel(actionType, lang);
  }
  return summary;
};

export const withAuditActionTypeLabel = <T extends { actionType?: string; action_type?: string }>(log: T, lang: string = 'zh-CN') => {
  const actionType = log.actionType || log.action_type;
  return {
    ...log,
    actionTypeLabel: getAuditActionTypeLabel(actionType, lang),
  };
};
