from backend.core.prompt_resolver import LocalizedPromptProxy

BUSINESS_OBJECT_WITHOUT_USAGE_SYSTEM_PROMPT = LocalizedPromptProxy("business_object_without_usage_system")
BUSINESS_OBJECT_WITHOUT_USAGE_USER_PROMPT_TEMPLATE = LocalizedPromptProxy("business_object_without_usage_user")
