from backend.core.prompt_resolver import LocalizedPromptProxy

FLOW_WITHOUT_STEPS_SYSTEM_PROMPT = LocalizedPromptProxy("flow_without_steps_system")
FLOW_WITHOUT_STEPS_USER_PROMPT_TEMPLATE = LocalizedPromptProxy("flow_without_steps_user")
